"""Initial migration.

Revision ID: 2695376c51c1
Revises: 
Create Date: 2021-07-28 15:29:25.442210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2695376c51c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wh')
    # ### end Alembic commands ###
