"""empty message

Revision ID: beaf3425fd83
Revises: 2695376c51c1
Create Date: 2021-07-28 17:01:04.706732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaf3425fd83'
down_revision = '2695376c51c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wh', sa.Column('cost', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wh', 'cost')
    # ### end Alembic commands ###
